VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "cAutoReportItem"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Const COL_SERIAL = 0
Const COL_ROOM = 0.75
Const COL_RESIDENT = 1.5
Const COL_EVENT = 3.5
Const COL_ALARMTIME = 6.5
Const COL_CANCELTIME = 7.5
Const COL_ELAPSEDTIME = 8.5
Const COL_OPERATOR = 8.75
